# CloudFormation template to create the required IAM Roles
# 1) CloudFormation execution role

AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CloudFromationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudFormationRolePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
              - s3:*
              - apigateway:*
              - lambda:*
              - iam:PassRole
              - kms:*
            Resource: "*"
      Roles:
        - !Ref CloudFromationRole
